default: &default
  adapter: mysql2
  username: rails
  password: anonymous
  timeout: 5000
  host: 127.0.0.1
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: efemerides_dev

test:
  <<: *default
  database: efemerides_test

production:
  <<: *default
  database: efemerides
